# Branch Protection Rules for SmartCloudOps AI
# Phase 3: CI/CD & Release Engineering

# Main branch protection
main:
  required_status_checks:
    strict: true
    contexts:
      - "🔍 Enhanced Quality Gate"
      - "🧪 Enhanced Backend Testing"
      - "🧪 Enhanced Frontend Testing"
      - "🏗️ Enhanced Build with SBOM"
      - "🧪 Enhanced Infrastructure Validation"
  
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  restrictions:
    users: []
    teams: []
  
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  
  # Require signed commits
  required_signatures: true
  
  # Require up-to-date branches
  require_branches_up_to_date: true

# Develop branch protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - "🔍 Enhanced Quality Gate"
      - "🧪 Enhanced Backend Testing"
      - "🧪 Enhanced Frontend Testing"
      - "🏗️ Enhanced Build with SBOM"
  
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
  
  restrictions:
    users: []
    teams: []
  
  required_linear_history: false
  allow_force_pushes: false
  allow_deletions: false
  
  # Require signed commits
  required_signatures: true
  
  # Require up-to-date branches
  require_branches_up_to_date: true

# Feature branch protection (for branches starting with feature/)
feature/*:
  required_status_checks:
    strict: false
    contexts:
      - "🔍 Enhanced Quality Gate"
      - "🧪 Enhanced Backend Testing"
  
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  restrictions:
    users: []
    teams: []
  
  required_linear_history: false
  allow_force_pushes: true
  allow_deletions: true
  
  # Don't require signed commits for feature branches
  required_signatures: false
  
  # Don't require up-to-date branches for feature branches
  require_branches_up_to_date: false

# Hotfix branch protection (for branches starting with hotfix/)
hotfix/*:
  required_status_checks:
    strict: true
    contexts:
      - "🔍 Enhanced Quality Gate"
      - "🧪 Enhanced Backend Testing"
      - "🏗️ Enhanced Build with SBOM"
  
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  restrictions:
    users: []
    teams: []
  
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  
  # Require signed commits for hotfixes
  required_signatures: true
  
  # Require up-to-date branches for hotfixes
  require_branches_up_to_date: true

# Release branch protection (for branches starting with release/)
release/*:
  required_status_checks:
    strict: true
    contexts:
      - "🔍 Enhanced Quality Gate"
      - "🧪 Enhanced Backend Testing"
      - "🧪 Enhanced Frontend Testing"
      - "🏗️ Enhanced Build with SBOM"
      - "🧪 Enhanced Infrastructure Validation"
  
  enforce_admins: false
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  restrictions:
    users: []
    teams: []
  
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  
  # Require signed commits for releases
  required_signatures: true
  
  # Require up-to-date branches for releases
  require_branches_up_to_date: true
