# SmartCloudOps AI - Staging Environment Values

# Backend configuration for staging
backend:
  replicaCount: 2
  
  image:
    repository: smartcloudops/backend
    tag: "staging"
    pullPolicy: IfNotPresent
    
  resources:
    requests:
      cpu: 150m
      memory: 384Mi
    limits:
      cpu: 750m
      memory: 768Mi
      
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    
  env:
    FLASK_ENV: staging
    PROMETHEUS_URL: http://prometheus:9090
    REQUIRE_APPROVAL: "true"
    MAX_ACTIONS_PER_HOUR: "5"
    COOLDOWN_MINUTES: "5"

# Frontend configuration for staging
frontend:
  replicaCount: 2
  
  image:
    repository: smartcloudops/frontend
    tag: "staging"
    pullPolicy: IfNotPresent
    
  resources:
    requests:
      cpu: 75m
      memory: 192Mi
    limits:
      cpu: 375m
      memory: 384Mi
      
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

# Ingress for staging
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: smartcloudops-staging.example.com
      paths:
        - path: /api
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
  tls:
    - secretName: smartcloudops-staging-tls
      hosts:
        - smartcloudops-staging.example.com

# Database for staging
postgresql:
  enabled: true
  auth:
    database: "cloudops_staging"
  primary:
    persistence:
      enabled: true
      size: 15Gi
    resources:
      requests:
        cpu: 200m
        memory: 384Mi
      limits:
        cpu: 750m
        memory: 768Mi

# Redis for staging
redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: 75m
        memory: 192Mi
      limits:
        cpu: 375m
        memory: 384Mi

# Monitoring for staging
monitoring:
  prometheus:
    enabled: true
    server:
      persistentVolume:
        size: 30Gi
      resources:
        requests:
          cpu: 300m
          memory: 768Mi
        limits:
          cpu: 1500m
          memory: 1536Mi
          
  grafana:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 750m
        memory: 768Mi

# Security (moderate for staging)
security:
  networkPolicies:
    enabled: true
