apiVersion: v1
kind: Namespace
metadata:
  name: smartcloudops
  labels:
    name: smartcloudops
    version: "3.0.0"
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smartcloudops-config
  namespace: smartcloudops
data:
  DATABASE_URL: "postgresql://smartcloudops:${POSTGRES_PASSWORD}@postgres:5432/smartcloudops"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379/0"
  FLASK_ENV: "production"
  GUNICORN_WORKERS: "4"
  GUNICORN_THREADS: "2"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: smartcloudops-secrets
  namespace: smartcloudops
type: Opaque
data:
  # These should be provided via external secret management (e.g., AWS Secrets Manager, HashiCorp Vault)
  # DO NOT commit actual secrets to version control
  # Example: SECRET_KEY should be base64 encoded and provided via CI/CD
  SECRET_KEY: ${SECRET_KEY_BASE64}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BASE64}
  REDIS_PASSWORD: ${REDIS_PASSWORD_BASE64}
  GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD_BASE64}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: smartcloudops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: smartcloudops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: smartcloudops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
