apiVersion: v1
kind: Namespace
metadata:
  name: smartcloudops
  labels:
    name: smartcloudops
    environment: production
    project: smartcloudops-ai
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: smartcloudops-quota
  namespace: smartcloudops
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: smartcloudops-limits
  namespace: smartcloudops
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
