"""Create anomalies and remediation tables

Revision ID: 06839fd37ff9
Revises: 
Create Date: 2025-08-23 18:41:36.581864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06839fd37ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'major', 'minor', 'info', name='anomalyseverity'), nullable=False),
    sa.Column('status', sa.Enum('active', 'acknowledged', 'resolved', 'dismissed', name='anomalystatus'), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('restart', 'scale', 'cleanup', 'config', name='remediationcategory'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='remediationseverity'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('can_override', sa.Boolean(), nullable=False),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('max_executions_per_hour', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'pending_approval', 'running', 'success', 'failed', 'stopped', name='remediationstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('target_service', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_name', sa.String(length=200), nullable=False),
    sa.Column('target_service', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('executed_by', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('remediation_action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['remediation_action_id'], ['remediation_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    op.drop_table('remediation_actions')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
