# Smart CloudOps AI - Prometheus Alert Rules
# These rules define when to trigger alerts for system anomalies

groups:
  - name: smartcloudops.rules
    rules:
      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 3m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 3 minutes on {{ $labels.instance }}"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 95% for more than 2 minutes on {{ $labels.instance }}"

      # High Disk Usage Alert
      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High disk usage detected on {{ $labels.instance }}"
          description: "Disk usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # Instance Down Alert
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute"

      # Flask Application Down Alert
      - alert: FlaskAppDown
        expr: up{job="flask-application"} == 0
        for: 1m
        labels:
          severity: critical
          service: application
        annotations:
          summary: "Flask application is down"
          description: "Flask application on {{ $labels.instance }} has been down for more than 1 minute"

      # High Request Rate Alert
      - alert: HighRequestRate
        expr: rate(flask_requests_total[5m]) > 100
        for: 2m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High request rate detected"
          description: "Flask application is receiving more than 100 requests per second for more than 2 minutes"

      # High Request Duration Alert
      - alert: HighRequestDuration
        expr: histogram_quantile(0.95, rate(flask_request_duration_seconds_bucket[5m])) > 1
        for: 3m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High request duration detected"
          description: "95th percentile request duration is above 1 second for more than 3 minutes"