{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smartcloudops-ai.fullname" . }}-backend-secret
  labels:
    {{- include "smartcloudops-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  secret-key: {{ randAlphaNum 32 | b64enc }}
  jwt-secret-key: {{ randAlphaNum 32 | b64enc }}
  database-url: {{ printf "postgresql+psycopg://cloudops:%s@%s-postgresql:5432/cloudops" (randAlphaNum 16) (include "smartcloudops-ai.fullname" .) | b64enc }}
  redis-password: {{ randAlphaNum 16 | b64enc }}
  openai-api-key: {{ "sk-placeholder-openai-key" | b64enc }}
  gemini-api-key: {{ "placeholder-gemini-key" | b64enc }}
{{- end }}
