# SmartCloudOps AI - Kubernetes Autoscaling
# Phase 3 Week 5: Infrastructure as Code (IaC) - Autoscaling Configuration

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartcloudops-api-hpa
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: smartcloudops-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartcloudops-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
    # CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Memory utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    # Custom metrics from Prometheus
    - type: Pods
      pods:
        metric:
          name: flask_request_duration_seconds
        target:
          type: AverageValue
          averageValue: "500m"  # 500ms average response time
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartcloudops-worker-hpa
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: smartcloudops-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartcloudops-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    # Memory utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    # Custom queue length metric
    - type: Object
      object:
        metric:
          name: celery_queue_length
        target:
          type: Value
          value: "10"
        describedObject:
          apiVersion: v1
          kind: Service
          name: smartcloudops-worker
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Longer stabilization for workers
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smartcloudops-api-pdb
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: disruption-budget
    app.kubernetes.io/part-of: smartcloudops-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: smartcloudops-ai
      app.kubernetes.io/component: api-server

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smartcloudops-worker-pdb
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: disruption-budget
    app.kubernetes.io/part-of: smartcloudops-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smartcloudops-ai
      app.kubernetes.io/component: worker

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: smartcloudops-worker-scaler
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: keda-scaler
    app.kubernetes.io/part-of: smartcloudops-platform
spec:
  scaleTargetRef:
    name: smartcloudops-worker
  pollingInterval: 30
  cooldownPeriod: 300
  idleReplicaCount: 1
  minReplicaCount: 2
  maxReplicaCount: 15
  triggers:
    # Redis queue length trigger
    - type: redis
      metadata:
        address: smartcloudops-redis.xyz.cache.amazonaws.com:6379
        listName: celery_tasks
        listLength: "5"
        enableTLS: "true"
      authenticationRef:
        name: redis-auth
    # Prometheus query trigger
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.smartcloudops-monitoring.svc.cluster.local:9090
        metricName: celery_queue_length
        threshold: "8"
        query: sum(celery_queue_length{queue="default"})
    # CPU trigger
    - type: cpu
      metadata:
        type: Utilization
        value: "80"

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-auth
  namespace: smartcloudops
spec:
  secretTargetRef:
    - parameter: password
      name: smartcloudops-secrets
      key: REDIS_PASSWORD

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcloudops-api
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: smartcloudops-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/smartcloudops-api-role

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartcloudops-worker
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: smartcloudops-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/smartcloudops-worker-role

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: smartcloudops
  name: smartcloudops-role
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: smartcloudops-platform
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smartcloudops-binding
  namespace: smartcloudops
  labels:
    app.kubernetes.io/name: smartcloudops-ai
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: smartcloudops-platform
subjects:
  - kind: ServiceAccount
    name: smartcloudops-api
    namespace: smartcloudops
  - kind: ServiceAccount
    name: smartcloudops-worker
    namespace: smartcloudops
roleRef:
  kind: Role
  name: smartcloudops-role
  apiGroup: rbac.authorization.k8s.io
