name: Infrastructure CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'

jobs:
  terraform-basic:
    name: Basic Terraform Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Format Check
      id: fmt
      run: |
        echo "::group::Terraform format check"
        terraform fmt -check -recursive terraform/ || echo "Terraform formatting issues found, but continuing..."
        echo "::endgroup::"
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        echo "::group::Terraform init"
        cd terraform/
        terraform init -backend=false || echo "Terraform init failed, but continuing..."
        echo "::endgroup::"
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      run: |
        echo "::group::Terraform validate"
        cd terraform/
        terraform validate || echo "Terraform validation failed, but continuing..."
        echo "::endgroup::"
      continue-on-error: true

  terraform-plan:
    name: Terraform Plan (AWS Required)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      id: init
      run: |
        echo "::group::Terraform init"
        cd terraform/
        terraform init || echo "Terraform init failed, but continuing..."
        echo "::endgroup::"
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      run: |
        echo "::group::Terraform plan"
        cd terraform/
        terraform plan -no-color -out=tfplan || echo "Terraform plan failed, but continuing..."
        echo "::endgroup::"
      continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
        AWS_REGION: ${{ secrets.AWS_REGION || 'us-west-2' }}

    - name: Comment PR
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`terraform
          ${{ steps.plan.outputs.stdout || 'Plan failed or no changes detected' }}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
        framework: terraform
      continue-on-error: true