name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'Dockerfile.production'
      - '.github/workflows/ecr-build-push.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-west-2' }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY || 'smartcloudops-ai-app' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          REPO_NAME=${ECR_REPOSITORY}
          docker build -f Dockerfile.production -t $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$REPO_NAME:latest
          docker push $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPO_NAME:latest

      - name: Output image URI
        run: echo "Image pushed: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"

