name: Simple Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test Python import
      run: |
        python -c "from app.main import app; print('✅ Flask app imported successfully')"
        
    - name: Test Node.js
      run: |
        cd smartcloudops-ai
        npm ci --legacy-peer-deps
        npm run build
